# Generated by Django 3.0.4 on 2020-04-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('type', models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdrawal')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
