# Generated by Django 3.0.2 on 2020-01-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-last_name']},
        ),
    ]
