# Generated by Django 3.0.2 on 2020-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200115_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='book',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
