# Generated by Django 3.0.2 on 2020-01-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200122_1422'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='book',
            order_with_respect_to='authors',
        ),
    ]
