# Generated by Django 3.0.2 on 2020-01-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200122_1423'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='book',
            order_with_respect_to=None,
        ),
    ]
