# Generated by Django 3.2.5 on 2021-07-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210719_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
