# Generated by Django 3.0.4 on 2020-03-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200202_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_published',
            new_name='published',
        ),
    ]
