# Generated by Django 3.2.5 on 2021-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
