# Generated by Django 3.2.5 on 2021-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
